steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
- name: python
  entrypoint: python
  args: ["pipeline_upload.py"]
options:
  logging: CLOUD_LOGGING_ONLY
